## Spatial Data Science (GEO6119)

---

# Lecture 2: Array and Data Frame

<br>
Instructor: Yi Qiang (qiangy@usf.edu)<br>

___

# Recap of Lab 1

### Variables
What will be the output of the following codes?


In [60]:
a = 3
b = "hello"
c = str(a) + b
print (c)

3hello


In [61]:
a = 100
b = a + 1
a > b

False

In [62]:
a = ["Hello","World", 2022]

In [63]:
#a[1]
a[0][1]

'e'

In [64]:
x = 5
for i in range(x):
    if i%2 == 0:
        print(x)
    else:
        print(i)

5
1
5
3
5


# 1. Numpy Array

- A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.
- An array can be 1-dimensional, 2-dimensional or n-dimensional. For instance, a raster is essentially a geo-coordinated 2D array.
- Arrays support element-wise operations that is not supported by other python data collections (e.g. list)

## 1.1 Create an array
### Creating from a list of the same data type

In [65]:
# Import the Numpy library
import numpy as np

In [66]:
# Create a list of numbers and print it
ls = [69,88,73,90,82,73]
print(ls)
print(type(ls))

[69, 88, 73, 90, 82, 73]
<class 'list'>


In [67]:
# Convert the list to numpy array and print it
a = np.array(ls)

In [68]:
print(a)

[69 88 73 90 82 73]


In [69]:
# print the data type in the array
print(type(a))

<class 'numpy.ndarray'>


### Create a 2D array

In [70]:
array2D = np.array([[1, 2, 3], [4, 5, 6]])
print(array2D)

[[1 2 3]
 [4 5 6]]


In [71]:
# Get the shape of the array
array2D.shape

(2, 3)

### Create an array of zeros, ones and a random array

In [72]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [73]:
# Create an 3*4 array of zeros
zeros = np.zeros((3,4))

# Create an 4*3 array of ones
ones = np.ones((4,3))

# Create a 5*2 array of random numbers
ran = np.random.rand(5,2)

In [74]:
print(zeros)
print(ones)
print(ran)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.0487553  0.08819725]
 [0.18850237 0.0269737 ]
 [0.92313713 0.08171132]
 [0.45864197 0.60968153]
 [0.07643721 0.42846857]]


### Values in an array must be in the same type

In [75]:
ls = [69,'second',73,90,82,73]
a = np.array(ls)

## 1.2 Arithmetic Operation on Array

In [76]:
array = np.array([69, 88, 73, 90, 82, 73])

# Each element adds 5
print(array + 5)

# Each element times 2
print(array*2)

# Each element 
print(array**2)

[74 93 78 95 87 78]
[138 176 146 180 164 146]
[4761 7744 5329 8100 6724 5329]


### You can't do arithmatic operations directly to list.

In [77]:
ls=[69,88,73,90,82,73]
np.array(ls) + 5

array([74, 93, 78, 95, 87, 78])

### Element-wise multiplication

In [78]:
array1 = np.array([[1, 1], [2, 2]])
array2 = np.array([[3, 3], [4, 4]])

# element-wise
np.multiply(array1,array2)

array([[3, 3],
       [8, 8]])

In [79]:
# does the same thing as numpy.mutiply
array1*array2

array([[3, 3],
       [8, 8]])

### Matrix multiplication

In [80]:
array1

array([[1, 1],
       [2, 2]])

In [81]:
array2

array([[3, 3],
       [4, 4]])

In [82]:
np.dot(array1,array2)

array([[ 7,  7],
       [14, 14]])

### More arithmetic operators

In [83]:
array1

array([[1, 1],
       [2, 2]])

In [84]:
np.sqrt(array1)

array([[1.        , 1.        ],
       [1.41421356, 1.41421356]])

In [85]:
array

array([69, 88, 73, 90, 82, 73])

In [86]:
# Sum of an array
print(array.sum())

# Maximum value
print(array.max())

# Mean
print(array.mean())

# Mean of a slice
print(array[0:3].mean())

475
90
79.16666666666667
76.66666666666667


### Comparison operator

In [87]:
# Comparing array1 and array2
array1 > array2

array([[False, False],
       [False, False]])

### Aggregation operators

In [88]:
# Aggregate array

## 1.3 Accessing attributes of an array

In [89]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [90]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
# Shape of an array
print(array.shape)
# Total number of values
print(array.size)
# Number of dimensions
print(array.ndim)
# Type of values
print(array.dtype)

(3, 4)
12
2
int32


## 1.4 Array Indexing

In [92]:
# Create an 1D array
array = np.array([3,4,2,6,8,1,7,5])
array

array([3, 4, 2, 6, 8, 1, 7, 5])

In [93]:
# First element
array[0]

3

In [94]:
# Last element
array[-1]

5

In [95]:
# First 3 elements
array[:3]

array([3, 4, 2])

In [96]:
# Elements from the 4th element
array[3:]

array([6, 8, 1, 7, 5])

In [97]:
# Elements from the 4rd to the 8th
array[3:8]

array([6, 8, 1, 7, 5])

In [98]:
# Create a 2D array in a shape of 4 rows*5 columns
array = np.random.rand(4,5)
array

array([[0.41270266, 0.87011915, 0.69330426, 0.62771982, 0.10998608],
       [0.90122301, 0.85945728, 0.0642507 , 0.64769748, 0.2610871 ],
       [0.61556184, 0.88876477, 0.37273154, 0.94534146, 0.94790115],
       [0.87000748, 0.97495395, 0.72353194, 0.28532653, 0.24784616]])

In [99]:
# The element in the 1st row and 2nd column
array[0,1]

0.8701191464526128

In [100]:
# The element in the last row and the 2nd column
array[-1,1]

0.9749539506519446

In [101]:
# All elements in the 3rd row
array[2,:] = 1


In [102]:
# Elements from the 2nd to the 3rd row and from the 1st to the 2nd column
array[1:3,0:2]

array([[0.90122301, 0.85945728],
       [1.        , 1.        ]])

## 1.5 Boolean comparison and selection

In [103]:
# Comparing each element with 0.5, 
# If greater than 0.5, return True
# If not, return False
array > 0.5

array([[False,  True,  True,  True, False],
       [ True,  True, False,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False]])

In [104]:
# Return all elements greater than 0.5
array[array>0.5]

array([0.87011915, 0.69330426, 0.62771982, 0.90122301, 0.85945728,
       0.64769748, 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.87000748, 0.97495395, 0.72353194])

In [105]:
# Return all elements greater than 0.5 and smaller than or equal to 0.8
array[~(array<=0.5)]

array([0.87011915, 0.69330426, 0.62771982, 0.90122301, 0.85945728,
       0.64769748, 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.87000748, 0.97495395, 0.72353194])

# 2. Pandas DataFrame


- Built on 2D numpy array.
- A data structure designed for spreadsheet and tables
- A column in a dataframe is a 1-dimensional labeled array
- Different columns in a DataFrame can store different types of values (integer, string, date/time...)

## 2.1 Create or Import a Importing DataFrame

In [106]:
# import the package of pandas
import pandas as pd

# Create a DataFrame
df = pd.DataFrame(
    [['Mike', 28, True],
     ['Emma', 26, False],
     ['Jake', 29, False]],
    index=[1, 2, 3],
    columns=['Name', 'Age', 'Vegetarian'])

In [107]:
df

Name  Age  Vegetarian
1  Mike   28        True
2  Emma   26       False
3  Jake   29       False

In [108]:
# read the spreadsheet
df = pd.read_csv('other\purchase.csv')

In [109]:
# Preview the first 5 rows
df.head()

OrderDate   Region      Rep    Item  Units  Unit Cost   Total
0   1/6/2018     East    Jones  Pencil     95       1.99  189.05
1  1/23/2018  Central   Kivell  Binder     50      19.99  999.50
2   2/9/2018  Central  Jardine  Pencil     36       4.99  179.64
3  2/26/2018  Central     Gill     Pen     27      19.99  539.73
4  3/15/2018     West  Sorvino  Pencil     56       2.99  167.44

## 2.2 DataFrame Indexing and Slicing

#### Get a column by name

In [110]:
# Getting a column by name, return a Series
df['Unit Cost']

0       1.99
1      19.99
2       4.99
3      19.99
4       2.99
5       4.99
6       1.99
7       4.99
8       1.99
9       8.99
10      4.99
11      1.99
12     19.99
13      4.99
14    125.00
15     15.99
16      8.99
17      8.99
18     19.99
19      4.99
20      1.29
21     15.99
22      8.99
23     15.00
24      4.99
25     19.99
26      4.99
27      1.99
28      4.99
29      1.29
30      8.99
31    125.00
32      4.99
33     12.49
34     23.95
35    275.00
36      1.29
37      1.99
38     19.99
39      1.29
40      4.99
41     19.99
42      4.99
Name: Unit Cost, dtype: float64

In [111]:
# Another way of getting a column by name, return a Series
df['Unit Cost']

0       1.99
1      19.99
2       4.99
3      19.99
4       2.99
5       4.99
6       1.99
7       4.99
8       1.99
9       8.99
10      4.99
11      1.99
12     19.99
13      4.99
14    125.00
15     15.99
16      8.99
17      8.99
18     19.99
19      4.99
20      1.29
21     15.99
22      8.99
23     15.00
24      4.99
25     19.99
26      4.99
27      1.99
28      4.99
29      1.29
30      8.99
31    125.00
32      4.99
33     12.49
34     23.95
35    275.00
36      1.29
37      1.99
38     19.99
39      1.29
40      4.99
41     19.99
42      4.99
Name: Unit Cost, dtype: float64

In [112]:
# Another way of getting a column by name, return a DataFrame
df[['Units']]

Units
0      95
1      50
2      36
3      27
4      56
5      60
6      75
7      90
8      32
9      60
10     90
11     29
12     81
13     35
14      2
15     16
16     28
17     64
18     15
19     96
20     67
21     74
22     46
23     87
24      4
25      7
26     50
27     66
28     96
29     53
30     80
31      5
32     62
33     55
34     42
35      3
36      7
37     76
38     57
39     14
40     11
41     94
42     28

### Getting multiple columns

In [113]:
# Getting multiple columns by name
df[['OrderDate','Region','Rep','Units','Unit Cost']]

OrderDate   Region       Rep  Units  Unit Cost
0     1/6/2018     East     Jones     95       1.99
1    1/23/2018  Central    Kivell     50      19.99
2     2/9/2018  Central   Jardine     36       4.99
3    2/26/2018  Central      Gill     27      19.99
4    3/15/2018     West   Sorvino     56       2.99
5     4/1/2018     East     Jones     60       4.99
6    4/18/2018  Central   Andrews     75       1.99
7     5/5/2018  Central   Jardine     90       4.99
8    5/22/2018     West  Thompson     32       1.99
9     6/8/2018     East     Jones     60       8.99
10   6/25/2018  Central    Morgan     90       4.99
11   7/12/2018     East    Howard     29       1.99
12   7/29/2018     East    Parent     81      19.99
13   8/15/2018     East     Jones     35       4.99
14    9/1/2018  Central     Smith      2     125.00
15   9/18/2018     East     Jones     16      15.99
16   10/5/2018  Central    Morgan     28       8.99
17  10/22/2018     East     Jones     64       8.99
18   11/8/2018     East    Parent     15      19.99
19  11/25/2018  Central    Kivell     96       4.99
20  12/12/2018  Central     Smith     67       1.29
21  12/29/2018     East    Parent     74      15.99
22   1/15/2019  Central      Gill     46       8.99
23    2/1/2019  Central     Smith     87      15.00
24   2/18/2019     East     Jones      4       4.99
25    3/7/2019     West   Sorvino      7      19.99
26   3/24/2019  Central   Jardine     50       4.99
27   4/10/2019  Central   Andrews     66       1.99
28   4/27/2019     East    Howard     96       4.99
29   5/14/2019  Central      Gill     53       1.29
30   5/31/2019  Central      Gill     80       8.99
31   6/17/2019  Central    Kivell      5     125.00
32    7/4/2019     East     Jones     62       4.99
33   7/21/2019  Central    Morgan     55      12.49
34    8/7/2019  Central    Kivell     42      23.95
35   8/24/2019     West   Sorvino      3     275.00
36   9/10/2019  Central      Gill      7       1.29
37   9/27/2019     West   Sorvino     76       1.99
38  10/14/2019     West  Thompson     57      19.99
39  10/31/2019  Central   Andrews     14       1.29
40  11/17/2019  Central   Jardine     11       4.99
41   12/4/2019  Central   Jardine     94      19.99
42  12/21/2019  Central   Andrews     28       4.99

In [114]:
# Getting columns using the .loc function
df.loc[:,['OrderDate','Rep','Units']]

OrderDate       Rep  Units
0     1/6/2018     Jones     95
1    1/23/2018    Kivell     50
2     2/9/2018   Jardine     36
3    2/26/2018      Gill     27
4    3/15/2018   Sorvino     56
5     4/1/2018     Jones     60
6    4/18/2018   Andrews     75
7     5/5/2018   Jardine     90
8    5/22/2018  Thompson     32
9     6/8/2018     Jones     60
10   6/25/2018    Morgan     90
11   7/12/2018    Howard     29
12   7/29/2018    Parent     81
13   8/15/2018     Jones     35
14    9/1/2018     Smith      2
15   9/18/2018     Jones     16
16   10/5/2018    Morgan     28
17  10/22/2018     Jones     64
18   11/8/2018    Parent     15
19  11/25/2018    Kivell     96
20  12/12/2018     Smith     67
21  12/29/2018    Parent     74
22   1/15/2019      Gill     46
23    2/1/2019     Smith     87
24   2/18/2019     Jones      4
25    3/7/2019   Sorvino      7
26   3/24/2019   Jardine     50
27   4/10/2019   Andrews     66
28   4/27/2019    Howard     96
29   5/14/2019      Gill     53
30   5/31/2019      Gill     80
31   6/17/2019    Kivell      5
32    7/4/2019     Jones     62
33   7/21/2019    Morgan     55
34    8/7/2019    Kivell     42
35   8/24/2019   Sorvino      3
36   9/10/2019      Gill      7
37   9/27/2019   Sorvino     76
38  10/14/2019  Thompson     57
39  10/31/2019   Andrews     14
40  11/17/2019   Jardine     11
41   12/4/2019   Jardine     94
42  12/21/2019   Andrews     28

### Getting rows and columns

In [115]:
# Getting the rows with an index of 1 and 2
df.loc[[0,1],:]

OrderDate   Region     Rep    Item  Units  Unit Cost   Total
0   1/6/2018     East   Jones  Pencil     95       1.99  189.05
1  1/23/2018  Central  Kivell  Binder     50      19.99  999.50

In [116]:
# Getting the 1st to 10th rows
df[0:10]

OrderDate   Region       Rep    Item  Units  Unit Cost   Total
0   1/6/2018     East     Jones  Pencil     95       1.99  189.05
1  1/23/2018  Central    Kivell  Binder     50      19.99  999.50
2   2/9/2018  Central   Jardine  Pencil     36       4.99  179.64
3  2/26/2018  Central      Gill     Pen     27      19.99  539.73
4  3/15/2018     West   Sorvino  Pencil     56       2.99  167.44
5   4/1/2018     East     Jones  Binder     60       4.99  299.40
6  4/18/2018  Central   Andrews  Pencil     75       1.99  149.25
7   5/5/2018  Central   Jardine  Pencil     90       4.99  449.10
8  5/22/2018     West  Thompson  Pencil     32       1.99   63.68
9   6/8/2018     East     Jones  Binder     60       8.99  539.40

In [117]:
# Getting the 1, 3, 5 rows and the Rep, Item and Total column
df.loc[[1,3,5],['Rep','Item','Total']]

Rep    Item   Total
1  Kivell  Binder  999.50
3    Gill     Pen  539.73
5   Jones  Binder  299.40

In [118]:
# Getting OrderDate and Region from 1-10 rows
df[0:10][['OrderDate','Region']]

OrderDate   Region
0   1/6/2018     East
1  1/23/2018  Central
2   2/9/2018  Central
3  2/26/2018  Central
4  3/15/2018     West
5   4/1/2018     East
6  4/18/2018  Central
7   5/5/2018  Central
8  5/22/2018     West
9   6/8/2018     East

## 2.3 Query in DataFrame

Selecting rows where the Rep name is 'Jones'

In [119]:
# Select all records of Jones
df[df['Rep']=='Jones']

OrderDate Region    Rep     Item  Units  Unit Cost   Total
0     1/6/2018   East  Jones   Pencil     95       1.99  189.05
5     4/1/2018   East  Jones   Binder     60       4.99  299.40
9     6/8/2018   East  Jones   Binder     60       8.99  539.40
13   8/15/2018   East  Jones   Pencil     35       4.99  174.65
15   9/18/2018   East  Jones  Pen Set     16      15.99  255.84
17  10/22/2018   East  Jones      Pen     64       8.99  575.36
24   2/18/2019   East  Jones   Binder      4       4.99   19.96
32    7/4/2019   East  Jones  Pen Set     62       4.99  309.38

You can use & (and), | (or) and ~ (not) to combine conditions to sebset records

In [120]:
# Selecting all records of binders bought by Jones
df[(df.Rep=='Jones') & (df.Item=='Binder')]

OrderDate Region    Rep    Item  Units  Unit Cost   Total
5    4/1/2018   East  Jones  Binder     60       4.99  299.40
9    6/8/2018   East  Jones  Binder     60       8.99  539.40
24  2/18/2019   East  Jones  Binder      4       4.99   19.96

## 2.4 Summarize DataFrame

In [122]:
df.head()

OrderDate   Region      Rep    Item  Units  Unit Cost   Total
0   1/6/2018     East    Jones  Pencil     95       1.99  189.05
1  1/23/2018  Central   Kivell  Binder     50      19.99  999.50
2   2/9/2018  Central  Jardine  Pencil     36       4.99  179.64
3  2/26/2018  Central     Gill     Pen     27      19.99  539.73
4  3/15/2018     West  Sorvino  Pencil     56       2.99  167.44

In [124]:
# Calculate total cost from all records
df['Total'].sum()

19627.880000000005

In [ ]:
# Calculate average unit number
df.Units.mean()

In [ ]:
df.head()

In [ ]:
# Calculate the total cost of pencils made by Jones
df[(df.Item=='Pencil') & (df['Rep']=='Jones')].Total.sum()

In [135]:
# Counting number of records in each name
df['Rep'].value_counts()

Jones       8
Jardine     5
Gill        5
Andrews     4
Sorvino     4
Kivell      4
Morgan      3
Smith       3
Parent      3
Howard      2
Thompson    2
Name: Rep, dtype: int64

In [ ]:
# Get the shape of the DataFrame
df.shape

In [ ]:
# Get statistics of numeric values in columns
df.describe()

In [ ]:
# Get unique values in a column
df['Rep'].unique()

In [ ]:
# Get number of unique values in a column
df['Rep'].nunique()

## Useful materials

- Cheatsheet of Numpy Array https://assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf
- Cheatsheet of Data Frame https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf